image: node:latest

stages:
  - build

compile:
  stage: build
  script:
    - npm ci
    - cp .env.example .env
    - npm run build
  artifacts:
    paths:
      - node_modules
  only:
    - master
    - merge_requests
