image: node:latest

default:
  before_script:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir .pnpm-store

stages:
  - build
  - run

compile:
  stage: build
  script:
    - pnpm ci
    - cp .env.example .env
    - pnpm run build
  artifacts:
    paths:
      - node_modules

testrun:
  stage: run
  script:
    - pnpm run ci --if-present