image: node:latest

stages:
  - build
  - run

compile:
  stage: build
  script:
    - npm ci
    - cp .env.example .env
    - npm run build
  artifacts:
    paths:
      - node_modules

testrun:
  stage: run
  script:
    - npm run ci --if-present