image: node:latest

default:
  before_script:
  - corepack enable
  - corepack prepare pnpm@latest-9 --activate
  - pnpm config set store-dir .pnpm-store

stages:
  - build
  - run

compile:
  stage: build
  script:
    - npm ci
    - cp .env.example .env
    - npm run build
  artifacts:
    paths:
      - node_modules

testrun:
  stage: run
  script:
    - npm run ci --if-present